### ISSUE TITLE
MKS_0.22.1 does not allow Extraplanetary_Launchpads_v4.4.0

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [taniwha-qf/Extraplanetary-Launchpads#87] opened 2014-12-22 18:44 UTC
mks 0.22.1 does not allow Extraplanetary_Launchpads_v4.4.0 to to show in the VAB

**Comment by taniwha-qf** [comment] 2015-01-02 09:07
Closing as "not a bug" (need to add such a label)

**Closed by taniwha-qf** 2015-01-02 09:07 UTC
Labels: invalid
